# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  - binary: mite
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags: -s -w -X github.com/leanovate/mite-go/app.version={{.Version}} -X github.com/leanovate/mite-go/app.commit={{.Commit}} -X github.com/leanovate/mite-go/app.date={{.Date}}
archives:
  - id: foo
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
